version: "3.7"
services:
  fossnewsbot:
    image: "fossnewsbot:latest"
    build:
      context: .
    container_name: fossnewsbot
    hostname: fossnewsbot
    ports:
    - "3000:3000"
    environment:
      FOSSNEWSBOT_ENV: production
    restart: unless-stopped
  fossnewsbot-dev:
    image: "fossnewsbot-dev:latest"
    build:
      context: .
    container_name: fossnewsbot-dev
    hostname: fossnewsbot
    ports:
    - "3000:3000"
    environment:
      FOSSNEWSBOT_ENV: development
